// <auto-generated />
using System;
using EShop.Infra.Db.Sql.DbCtx;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShop.Infra.Db.Sql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShop.Domain.Core.BasketAgg.Entity.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("EShop.Domain.Core.BasketItemAgg.Entity.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("EShop.Domain.Core.CategoryAgg.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Name = "موبایل"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Name = "لپ تاپ"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Name = "لوازم  خانه"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Name = "لوازم بهداشتی"
                        });
                });

            modelBuilder.Entity("EShop.Domain.Core.OrderAgg.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EShop.Domain.Core.OrderItemAgg.Entity.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EShop.Domain.Core.ProductAgg.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "گوشی پرچمدار اپل با چیپ A17 Pro و دوربین قدرتمند",
                            IsDeleted = false,
                            Price = 49999.0,
                            Stock = 10,
                            Title = "iPhone 15 Pro"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "پرچمدار سامسونگ با دوربین 200 مگاپیکسل و نمایشگر Dynamic AMOLED",
                            IsDeleted = false,
                            Price = 45999.0,
                            Stock = 15,
                            Title = "Samsung Galaxy S24 Ultra"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "گوشی قدرتمند شیائومی با Snapdragon 8 Gen 3 و شارژ سریع 120 وات",
                            IsDeleted = false,
                            Price = 28999.0,
                            Stock = 20,
                            Title = "Xiaomi 14 Pro"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "گوشی گوگل با اندروید خالص و دوربین هوشمند مجهز به AI",
                            IsDeleted = false,
                            Price = 37999.0,
                            Stock = 12,
                            Title = "Google Pixel 9"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "گوشی سریع و سبک با OxygenOS و شارژ فوق سریع",
                            IsDeleted = false,
                            Price = 32999.0,
                            Stock = 18,
                            Title = "OnePlus 12"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "لپ‌تاپ قدرتمند اپل با چیپ M3 Pro و نمایشگر Retina",
                            IsDeleted = false,
                            Price = 89999.0,
                            Stock = 8,
                            Title = "MacBook Pro 16 M3"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "لپ‌تاپ حرفه‌ای دل با نمایشگر InfinityEdge و پردازنده Core i7 نسل 13",
                            IsDeleted = false,
                            Price = 74999.0,
                            Stock = 12,
                            Title = "Dell XPS 15"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "لپ‌تاپ ۲ در ۱ با طراحی باریک، صفحه لمسی و عمر باتری طولانی",
                            IsDeleted = false,
                            Price = 65999.0,
                            Stock = 10,
                            Title = "HP Spectre x360"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "لپ‌تاپ سبک و مقاوم با کیبورد حرفه‌ای و امنیت بالا",
                            IsDeleted = false,
                            Price = 69999.0,
                            Stock = 15,
                            Title = "Lenovo ThinkPad X1 Carbon"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "لپ‌تاپ گیمینگ ایسوس با کارت گرافیک RTX 4070 و خنک‌کننده پیشرفته",
                            IsDeleted = false,
                            Price = 79999.0,
                            Stock = 6,
                            Title = "Asus ROG Zephyrus G16"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "جاروبرقی رباتیک با قابلیت کنترل از طریق موبایل و برنامه‌ریزی روزانه",
                            IsDeleted = false,
                            Price = 12999.0,
                            Stock = 20,
                            Title = "جاروبرقی هوشمند شیائومی"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "مایکروویو دیجیتال با برنامه‌های پخت متنوع و صفحه نمایش لمسی",
                            IsDeleted = false,
                            Price = 8999.0,
                            Stock = 15,
                            Title = "مایکروویو سامسونگ 32 لیتری"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "یخچال فریزر بزرگ با سیستم خنک‌کننده هوشمند و مصرف انرژی پایین",
                            IsDeleted = false,
                            Price = 45999.0,
                            Stock = 8,
                            Title = "یخچال فریزر دو قلو ال‌جی"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "لباسشویی اتوماتیک با برنامه‌های شستشوی سریع و موتور کم‌صدا",
                            IsDeleted = false,
                            Price = 18999.0,
                            Stock = 12,
                            Title = "ماشین لباسشویی بوش 9 کیلویی"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "آبمیوه‌گیری حرفه‌ای با فیلتر استیل ضدزنگ و قابلیت شستشوی آسان",
                            IsDeleted = false,
                            Price = 4999.0,
                            Stock = 25,
                            Title = "آبمیوه‌گیری فیلیپس"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "مخلوط‌کن حرفه‌ای با تیغه استیل ضدزنگ و قابلیت خرد کردن یخ",
                            IsDeleted = false,
                            Price = 3499.0,
                            Stock = 25,
                            Title = "مخلوط‌کن فیلیپس"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "چای‌ساز دیجیتال با قابلیت تنظیم دما و خاموشی خودکار",
                            IsDeleted = false,
                            Price = 2799.0,
                            Stock = 18,
                            Title = "چای‌ساز بوش"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "غذاساز چندکاره با دیسک‌های مختلف برای خرد کردن، رنده و ورز دادن خمیر",
                            IsDeleted = false,
                            Price = 5999.0,
                            Stock = 10,
                            Title = "غذاساز کنوود"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "اجاق گاز ۵ شعله با طراحی شیشه‌ای و سیستم ایمنی ترموکوپل",
                            IsDeleted = false,
                            Price = 12999.0,
                            Stock = 7,
                            Title = "اجاق گاز رومیزی اسنوا"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = 1,
                            Description = "توستر دو خانه با قابلیت یخ‌زدایی و تنظیم درجه برشته شدن",
                            IsDeleted = false,
                            Price = 1999.0,
                            Stock = 20,
                            Title = "توستر نان پاناسونیک"
                        });
                });

            modelBuilder.Entity("EShop.Domain.Core.UserAgg.Entity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Balance = 0.0,
                            ConcurrencyStamp = "ebbe524b-b089-4342-ba6c-a1dbc9386d89",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "b@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "behnaz",
                            LastName = "bayatloo",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEP2c/joNrBvkfxNU2/sqj5Kxoh1h/Dtl7EpZIL5pYjHFw8rS2E/IsvvLYHottNemYg==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "8f6db601-5de7-417a-931f-fa67498f721f",
                            TwoFactorEnabled = false,
                            UserName = "behnaz"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Balance = 0.0,
                            ConcurrencyStamp = "15de2064-f5f7-4acd-88cf-99d8d633106e",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "beigi@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "meysam",
                            LastName = "beigi",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEAMBjlWwf/V1h4xsZsXd1Zvw3FZYfSUc/R6JbabDP1K0Bfwhf6M/TbGGHl1SXwJGqg==",
                            PhoneNumberConfirmed = false,
                            Role = 2,
                            SecurityStamp = "741063eb-e8b0-4dae-a2a4-b5fae0bfeff3",
                            TwoFactorEnabled = false,
                            UserName = "meysam"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EShop.Domain.Core.BasketAgg.Entity.Basket", b =>
                {
                    b.HasOne("EShop.Domain.Core.UserAgg.Entity.ApplicationUser", "User")
                        .WithMany("Baskets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Domain.Core.BasketItemAgg.Entity.BasketItem", b =>
                {
                    b.HasOne("EShop.Domain.Core.BasketAgg.Entity.Basket", "Basket")
                        .WithMany("BasketItems")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Domain.Core.ProductAgg.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Domain.Core.OrderAgg.Entity.Order", b =>
                {
                    b.HasOne("EShop.Domain.Core.UserAgg.Entity.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Domain.Core.OrderItemAgg.Entity.OrderItem", b =>
                {
                    b.HasOne("EShop.Domain.Core.OrderAgg.Entity.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Domain.Core.ProductAgg.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Domain.Core.ProductAgg.Entity.Product", b =>
                {
                    b.HasOne("EShop.Domain.Core.CategoryAgg.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("EShop.Domain.Core.UserAgg.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("EShop.Domain.Core.UserAgg.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Domain.Core.UserAgg.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("EShop.Domain.Core.UserAgg.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EShop.Domain.Core.BasketAgg.Entity.Basket", b =>
                {
                    b.Navigation("BasketItems");
                });

            modelBuilder.Entity("EShop.Domain.Core.CategoryAgg.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EShop.Domain.Core.OrderAgg.Entity.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EShop.Domain.Core.UserAgg.Entity.ApplicationUser", b =>
                {
                    b.Navigation("Baskets");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
